#Deployment postgre
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postagre
spec:
  selector:
    matchLabels:
      app: postgre
  template:
    metadata:
      labels:
        app: postgre
    spec:
      containers:
        - name: postgre
          image: postgre:14.3
          ports:
           - containerPort: 5232
          env:
          - name: POSTGRES_PASSWORD
            value: "conversaotemperatura"  
          - name: POSTGRES_USER
            value: "shurato"
          - name: POSTGRES_DB
            value: "naruto" 
---
apiVersion: v1
kind: Service
metadata:
  name: postgre
spec:
  selector:
    app: postgre
  ports:
  - port: 5232 
    targetPort: 5232
---     
apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversao-temperatura
spec:
  replicas: 12
  selector:
    matchLabels:
      app: conversao-temperatura
  template:
    metadata:
      labels:
        app: conversao-temperatura
    spec:
      containers:
      - name: conversao-temperatura
        image: mjpaall/conversao-temperatura:v1
      
--- 
apiVersion: v1
kind: Service
metadata:
  name: conversao-temperatura
spec:
  selector:
    app: conversao-temperatura
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30000
  type: NodePort     


